module Mcp
  # The MCP tool catalog. Each entry maps a tool name to an existing REST endpoint
  # (see Mcp::Tool). Grouped by scope. Adding a capability is a one-line addition
  # here — no new controller or dispatch code. Filtering by granted scopes and by
  # the user's admin status happens in the server controller, not here.
  module ToolRegistry
    OBJECT = { "type" => "object" }.freeze

    module_function

    def all
      @all ||= [
        # ── analytics ──────────────────────────────────────────────────────────
        t("dashboard_stats", "Overview metrics for the environment (messages, delivery, engagement).",
          scope: "analytics", method: :get, path: "/dashboard/stats"),

        # ── messaging ──────────────────────────────────────────────────────────
        t("send_message", "Send a message on any channel. Set type to email/sms/whatsapp/mobile_push/web_push.",
          scope: "messaging", method: :post, path: "/messages",
          schema: obj(
            { "type" => str_enum(%w[email sms whatsapp mobile_push web_push]),
              "to" => str("Recipient (email address or phone in E.164)."),
              "cc" => str, "bcc" => str,
              "subject" => str("Email subject."),
              "body" => str("Message body (HTML for email)."),
              "template_id" => int("Render a stored template instead of body."),
              "data" => OBJECT.merge("description" => "Variables for template rendering.") },
            required: %w[type to])),
        t("trigger_message", "Send a message by looking up a template by its trigger name.",
          scope: "messaging", method: :post, path: "/messages/trigger",
          schema: obj({ "trigger" => str, "to" => str, "data" => OBJECT }, required: %w[trigger to])),
        t("list_messages", "List messages with optional filters.",
          scope: "messaging", method: :get, path: "/messages",
          query: %w[page search channel status date_from date_to drip_id],
          schema: obj({ "page" => int, "search" => str, "channel" => str, "status" => str,
                        "date_from" => str, "date_to" => str })),
        t("get_message", "Fetch a single message and its per-recipient delivery outcomes.",
          scope: "messaging", method: :get, path: "/messages/{id}",
          path_params: %w[id], schema: obj({ "id" => int }, required: %w[id])),
        t("retry_message_delivery", "Retry delivery of a failed message.",
          scope: "messaging", method: :post, path: "/messages/{id}/retry_delivery",
          path_params: %w[id], schema: obj({ "id" => int }, required: %w[id])),
        t("delete_message", "Delete a message.",
          scope: "messaging", method: :delete, path: "/messages/{id}",
          path_params: %w[id], schema: obj({ "id" => int }, required: %w[id])),

        # ── templates ──────────────────────────────────────────────────────────
        t("list_templates", "List templates. Pass scope=account for all, or filter by channel.",
          scope: "templates", method: :get, path: "/templates", query: %w[scope channel],
          schema: obj({ "scope" => str, "channel" => str })),
        t("get_template", "Fetch one template.",
          scope: "templates", method: :get, path: "/templates/{id}",
          path_params: %w[id], schema: obj({ "id" => int }, required: %w[id])),
        t("create_template", "Create a template.",
          scope: "templates", method: :post, path: "/templates", body_key: "template",
          schema: obj({ "name" => str, "channel" => str, "subject" => str, "body" => str,
                        "trigger" => str, "layout_id" => int, "folder_id" => int,
                        "body_format" => str }, required: %w[name])),
        t("update_template", "Update a template.",
          scope: "templates", method: :patch, path: "/templates/{id}", body_key: "template",
          path_params: %w[id], schema: obj({ "id" => int, "name" => str, "subject" => str,
                                             "body" => str, "trigger" => str }, required: %w[id])),
        t("delete_template", "Delete a template.",
          scope: "templates", method: :delete, path: "/templates/{id}",
          path_params: %w[id], schema: obj({ "id" => int }, required: %w[id])),
        t("sync_templates", "Bulk upsert layouts + templates (markdown sync).",
          scope: "templates", method: :post, path: "/sync"),
        t("list_layouts", "List layouts.", scope: "templates", method: :get, path: "/layouts"),
        t("create_layout", "Create a layout.",
          scope: "templates", method: :post, path: "/layouts", body_key: "layout",
          schema: obj({ "name" => str, "body" => str }, required: %w[name])),
        t("update_layout", "Update a layout.",
          scope: "templates", method: :patch, path: "/layouts/{id}", body_key: "layout",
          path_params: %w[id], schema: obj({ "id" => int, "name" => str, "body" => str }, required: %w[id])),
        t("delete_layout", "Delete a layout.",
          scope: "templates", method: :delete, path: "/layouts/{id}",
          path_params: %w[id], schema: obj({ "id" => int }, required: %w[id])),
        t("list_folders", "List template folders.",
          scope: "templates", method: :get, path: "/folders", query: %w[nested environment_id]),
        t("create_folder", "Create a template folder.",
          scope: "templates", method: :post, path: "/folders", body_key: "folder",
          schema: obj({ "name" => str, "parent_folder_id" => int }, required: %w[name])),
        t("move_folder", "Move a folder under another folder.",
          scope: "templates", method: :post, path: "/folders/{id}/move",
          path_params: %w[id], schema: obj({ "id" => int, "target_folder_id" => int }, required: %w[id])),
        t("delete_folder", "Delete a folder.",
          scope: "templates", method: :delete, path: "/folders/{id}",
          path_params: %w[id], schema: obj({ "id" => int }, required: %w[id])),
        t("list_whatsapp_templates", "List approved WhatsApp templates from Meta.",
          scope: "templates", method: :get, path: "/whatsapp_templates"),

        # ── audience ───────────────────────────────────────────────────────────
        t("identify_customer", "Create or update a customer by email.",
          scope: "audience", method: :post, path: "/customers/identify",
          schema: obj({ "email" => str, "first_name" => str, "last_name" => str,
                        "custom_attributes" => OBJECT }, required: %w[email])),
        t("list_customers", "List/search customers.",
          scope: "audience", method: :get, path: "/customers", query: %w[q page per_page],
          schema: obj({ "q" => str, "page" => int, "per_page" => int })),
        t("get_customer", "Fetch a customer.",
          scope: "audience", method: :get, path: "/customers/{id}",
          path_params: %w[id], schema: obj({ "id" => int }, required: %w[id])),
        t("delete_customer", "Delete a customer.",
          scope: "audience", method: :delete, path: "/customers/{id}",
          path_params: %w[id], schema: obj({ "id" => int }, required: %w[id])),
        t("customer_recent_activities", "Recent customer activity feed.",
          scope: "audience", method: :get, path: "/customers/recent_activities"),
        t("export_customers", "Export customers as CSV.",
          scope: "audience", method: :get, path: "/customers/export"),
        t("unsubscribe_customer", "Unsubscribe a customer from all channels.",
          scope: "audience", method: :post, path: "/customers/{id}/unsubscribe_all",
          path_params: %w[id], schema: obj({ "id" => int }, required: %w[id])),
        t("toggle_customer_unsubscribe", "Toggle a customer's unsubscribe for one channel.",
          scope: "audience", method: :post, path: "/customers/{id}/toggle_unsubscribe",
          path_params: %w[id], schema: obj({ "id" => int, "channel" => str }, required: %w[id])),
        t("list_device_tokens", "List a customer's push device tokens.",
          scope: "audience", method: :get, path: "/device_tokens", query: %w[email platform app_id]),
        t("register_device_token", "Register a push device token for a customer.",
          scope: "audience", method: :post, path: "/device_tokens",
          schema: obj({ "email" => str, "token" => str, "platform" => str, "app_id" => str },
                      required: %w[email token platform])),
        t("unregister_device_token", "Unregister a push device token.",
          scope: "audience", method: :post, path: "/device_tokens/unregister",
          schema: obj({ "token" => str }, required: %w[token])),
        t("list_csv_imports", "List CSV import jobs.",
          scope: "audience", method: :get, path: "/csv_imports"),
        t("get_csv_import", "Fetch a CSV import job.",
          scope: "audience", method: :get, path: "/csv_imports/{id}",
          path_params: %w[id], schema: obj({ "id" => int }, required: %w[id])),

        # ── segments ───────────────────────────────────────────────────────────
        t("list_segments", "List segments.", scope: "segments", method: :get, path: "/segments"),
        t("get_segment", "Fetch a segment.",
          scope: "segments", method: :get, path: "/segments/{id}",
          path_params: %w[id], schema: obj({ "id" => int }, required: %w[id])),
        t("create_segment", "Create a segment from conditions.",
          scope: "segments", method: :post, path: "/segments",
          schema: obj({ "name" => str, "description" => str,
                        "conditions" => { "type" => "array" } }, required: %w[name])),
        t("update_segment", "Update a segment.",
          scope: "segments", method: :patch, path: "/segments/{id}",
          path_params: %w[id], schema: obj({ "id" => int, "name" => str, "description" => str,
                                             "conditions" => { "type" => "array" } }, required: %w[id])),
        t("delete_segment", "Delete a segment.",
          scope: "segments", method: :delete, path: "/segments/{id}",
          path_params: %w[id], schema: obj({ "id" => int }, required: %w[id])),
        t("preview_segment", "Preview how many customers match a set of conditions.",
          scope: "segments", method: :post, path: "/segments/preview",
          schema: obj({ "conditions" => { "type" => "array" } })),
        t("segment_attributes", "List customer attributes available for segment conditions.",
          scope: "segments", method: :get, path: "/segments/attributes"),
        t("clean_segment", "Recompute a segment's membership.",
          scope: "segments", method: :post, path: "/segments/{id}/clean",
          path_params: %w[id], schema: obj({ "id" => int }, required: %w[id])),

        # ── campaigns ──────────────────────────────────────────────────────────
        t("list_campaigns", "List broadcast campaigns.", scope: "campaigns", method: :get, path: "/campaigns"),
        t("get_campaign", "Fetch a campaign.",
          scope: "campaigns", method: :get, path: "/campaigns/{id}",
          path_params: %w[id], schema: obj({ "id" => int }, required: %w[id])),
        t("create_campaign", "Create a broadcast campaign.",
          scope: "campaigns", method: :post, path: "/campaigns",
          schema: obj({ "name" => str, "subject" => str, "content" => str, "segment_id" => int,
                        "channel" => str, "template_id" => int, "sending_identity_id" => int },
                      required: %w[name])),
        t("update_campaign", "Update a campaign (not allowed once sent).",
          scope: "campaigns", method: :patch, path: "/campaigns/{id}",
          path_params: %w[id], schema: obj({ "id" => int, "name" => str, "subject" => str,
                                             "content" => str }, required: %w[id])),
        t("delete_campaign", "Delete a campaign.",
          scope: "campaigns", method: :delete, path: "/campaigns/{id}",
          path_params: %w[id], schema: obj({ "id" => int }, required: %w[id])),
        t("send_campaign", "Send a campaign to its segment.",
          scope: "campaigns", method: :post, path: "/campaigns/{id}/send_campaign",
          path_params: %w[id], schema: obj({ "id" => int }, required: %w[id])),
        t("send_campaign_test", "Send a test of a campaign to one customer.",
          scope: "campaigns", method: :post, path: "/campaigns/{id}/send_test",
          path_params: %w[id], schema: obj({ "id" => int, "customer_id" => int }, required: %w[id])),
        t("campaign_deliveries", "List per-recipient deliveries for a campaign.",
          scope: "campaigns", method: :get, path: "/campaigns/{id}/deliveries",
          path_params: %w[id], query: %w[status], schema: obj({ "id" => int, "status" => str }, required: %w[id])),
        t("retry_campaign_delivery", "Retry one failed campaign delivery.",
          scope: "campaigns", method: :post, path: "/campaigns/{id}/retry_delivery",
          path_params: %w[id], schema: obj({ "id" => int, "delivery_id" => int }, required: %w[id delivery_id])),
        t("retry_all_failed_campaign", "Retry all failed deliveries for a campaign.",
          scope: "campaigns", method: :post, path: "/campaigns/{id}/retry_all_failed",
          path_params: %w[id], schema: obj({ "id" => int }, required: %w[id])),

        # ── automations (drips + rules) ──────────────────────────────────────────
        t("list_drips", "List drip campaigns.", scope: "automations", method: :get, path: "/drips"),
        t("get_drip", "Fetch a drip campaign with its steps.",
          scope: "automations", method: :get, path: "/drips/{id}",
          path_params: %w[id], schema: obj({ "id" => int }, required: %w[id])),
        t("create_drip", "Create a drip campaign against a trigger segment.",
          scope: "automations", method: :post, path: "/drips",
          schema: obj({ "name" => str, "segment_id" => int, "steps" => { "type" => "array" },
                        "allow_reentry" => bool, "exit_on_segment_leave" => bool },
                      required: %w[name segment_id])),
        t("update_drip", "Update a drip campaign / its steps.",
          scope: "automations", method: :patch, path: "/drips/{id}",
          path_params: %w[id], schema: obj({ "id" => int, "name" => str, "steps" => { "type" => "array" } },
                                           required: %w[id])),
        t("delete_drip", "Delete a drip campaign.",
          scope: "automations", method: :delete, path: "/drips/{id}",
          path_params: %w[id], schema: obj({ "id" => int }, required: %w[id])),
        t("activate_drip", "Activate a drip campaign.",
          scope: "automations", method: :post, path: "/drips/{id}/activate",
          path_params: %w[id], schema: obj({ "id" => int }, required: %w[id])),
        t("pause_drip", "Pause a drip campaign.",
          scope: "automations", method: :post, path: "/drips/{id}/pause",
          path_params: %w[id], schema: obj({ "id" => int }, required: %w[id])),
        t("drip_projection", "Project how many customers a drip would enroll.",
          scope: "automations", method: :post, path: "/drips/projection",
          schema: obj({ "segment_id" => int })),
        t("list_rules", "List delivery/automation rules.",
          scope: "automations", method: :get, path: "/rules", query: %w[environment_id]),
        t("get_rule", "Fetch a rule.",
          scope: "automations", method: :get, path: "/rules/{id}",
          path_params: %w[id], schema: obj({ "id" => int }, required: %w[id])),
        t("create_rule", "Create a delivery rule.",
          scope: "automations", method: :post, path: "/rules", body_key: "rule",
          schema: obj({ "name" => str, "condition" => str, "outcome" => str, "scope" => str,
                        "active" => bool }, required: %w[condition outcome])),
        t("update_rule", "Update a delivery rule.",
          scope: "automations", method: :patch, path: "/rules/{id}", body_key: "rule",
          path_params: %w[id], schema: obj({ "id" => int, "condition" => str, "outcome" => str,
                                             "active" => bool }, required: %w[id])),
        t("delete_rule", "Delete a delivery rule.",
          scope: "automations", method: :delete, path: "/rules/{id}",
          path_params: %w[id], schema: obj({ "id" => int }, required: %w[id])),

        # ── channels (integrations, identities, environments) ─────────
        t("list_integrations", "List channel integrations.", scope: "channels", method: :get, path: "/integrations"),
        t("get_integration", "Fetch an integration.",
          scope: "channels", method: :get, path: "/integrations/{id}",
          path_params: %w[id], schema: obj({ "id" => int }, required: %w[id])),
        t("create_integration", "Create a channel integration (SES/SMTP/Twilio/WhatsApp/FCM/APNs/WebPush/MetaSocial).",
          scope: "channels", method: :post, path: "/integrations", body_key: "integration",
          schema: obj({ "type" => str, "kind" => str, "vendor" => str, "active" => bool,
                        "config" => OBJECT }, required: %w[type])),
        t("update_integration", "Update an integration.",
          scope: "channels", method: :patch, path: "/integrations/{id}", body_key: "integration",
          path_params: %w[id], schema: obj({ "id" => int, "active" => bool, "config" => OBJECT }, required: %w[id])),
        t("delete_integration", "Delete an integration.",
          scope: "channels", method: :delete, path: "/integrations/{id}",
          path_params: %w[id], schema: obj({ "id" => int }, required: %w[id])),
        t("test_integration", "Send a test message through an integration.",
          scope: "channels", method: :post, path: "/integrations/{id}/test",
          path_params: %w[id], schema: obj({ "id" => int, "to" => str }, required: %w[id to])),
        t("list_sending_identities", "List from-identities.", scope: "channels", method: :get, path: "/sending_identities"),
        t("create_sending_identity", "Create a from-identity.",
          scope: "channels", method: :post, path: "/sending_identities",
          schema: obj({ "from_name" => str, "from_email" => str, "is_default" => bool },
                      required: %w[from_email])),
        t("update_sending_identity", "Update a from-identity.",
          scope: "channels", method: :patch, path: "/sending_identities/{id}",
          path_params: %w[id], schema: obj({ "id" => int, "from_name" => str, "from_email" => str,
                                             "is_default" => bool }, required: %w[id])),
        t("delete_sending_identity", "Delete a from-identity.",
          scope: "channels", method: :delete, path: "/sending_identities/{id}",
          path_params: %w[id], schema: obj({ "id" => int }, required: %w[id])),
        t("list_environments", "List environments.", scope: "channels", method: :get, path: "/environments"),
        t("get_environment", "Fetch an environment.",
          scope: "channels", method: :get, path: "/environments/{id}",
          path_params: %w[id], schema: obj({ "id" => int }, required: %w[id])),
        t("toggle_environment_channel", "Enable/disable a channel default for an environment.",
          scope: "channels", admin: true, method: :post, path: "/environments/{id}/toggle_channel",
          path_params: %w[id], schema: obj({ "id" => int, "channel" => str }, required: %w[id channel])),

        # ── inbox (help desk) ───────────────────────────────────────────────────
        t("helpdesk_stats", "Help-desk summary stats.", scope: "inbox", method: :get, path: "/helpdesk/stats"),
        t("list_conversations", "List conversations.",
          scope: "inbox", method: :get, path: "/conversations", query: %w[status priority page assigned_user_id]),
        t("search_conversations", "Search conversations.",
          scope: "inbox", method: :get, path: "/conversations/search", query: %w[q]),
        t("conversation_stats", "Conversation counts by status.", scope: "inbox", method: :get, path: "/conversations/stats"),
        t("get_conversation", "Fetch a conversation.",
          scope: "inbox", method: :get, path: "/conversations/{id}",
          path_params: %w[id], schema: obj({ "id" => int }, required: %w[id])),
        t("update_conversation", "Update a conversation's status/priority.",
          scope: "inbox", method: :patch, path: "/conversations/{id}",
          path_params: %w[id], schema: obj({ "id" => int, "status" => str, "priority" => str }, required: %w[id])),
        t("conversation_messages", "List messages in a conversation.",
          scope: "inbox", method: :get, path: "/conversations/{id}/messages",
          path_params: %w[id], schema: obj({ "id" => int }, required: %w[id])),
        t("reply_conversation", "Post an operator reply to a conversation.",
          scope: "inbox", method: :post, path: "/conversations/{id}/create_message",
          path_params: %w[id], schema: obj({ "id" => int, "body" => str, "content" => str }, required: %w[id])),
        t("assign_conversation", "Assign a conversation to a user.",
          scope: "inbox", method: :post, path: "/conversations/{id}/assign",
          path_params: %w[id], schema: obj({ "id" => int, "user_id" => int }, required: %w[id])),
        t("snooze_conversation", "Snooze a conversation.",
          scope: "inbox", method: :post, path: "/conversations/{id}/snooze",
          path_params: %w[id], schema: obj({ "id" => int, "until" => str }, required: %w[id])),
        t("mark_conversation_read", "Mark a conversation read.",
          scope: "inbox", method: :post, path: "/conversations/{id}/mark_read",
          path_params: %w[id], schema: obj({ "id" => int }, required: %w[id])),
        t("add_conversation_tag", "Add a tag to a conversation.",
          scope: "inbox", method: :post, path: "/conversations/{id}/add_tag",
          path_params: %w[id], schema: obj({ "id" => int, "tag_id" => int }, required: %w[id tag_id])),
        t("list_mailboxes", "List help-desk mailboxes.", scope: "inbox", method: :get, path: "/mailboxes"),
        t("create_mailbox", "Connect a mailbox (IMAP/Gmail/Office365).",
          scope: "inbox", method: :post, path: "/mailboxes",
          schema: obj({ "provider" => str, "email" => str }, required: %w[provider email])),
        t("update_mailbox", "Update a mailbox.",
          scope: "inbox", method: :patch, path: "/mailboxes/{id}",
          path_params: %w[id], schema: obj({ "id" => int }, required: %w[id])),
        t("delete_mailbox", "Delete a mailbox.",
          scope: "inbox", method: :delete, path: "/mailboxes/{id}",
          path_params: %w[id], schema: obj({ "id" => int }, required: %w[id])),
        t("list_canned_responses", "List canned responses.", scope: "inbox", method: :get, path: "/canned_responses"),
        t("create_canned_response", "Create a canned response.",
          scope: "inbox", method: :post, path: "/canned_responses",
          schema: obj({ "shortcut" => str, "title" => str, "content" => str }, required: %w[content])),
        t("list_conversation_tags", "List conversation tags.", scope: "inbox", method: :get, path: "/conversation_tags"),
        t("create_conversation_tag", "Create a conversation tag.",
          scope: "inbox", method: :post, path: "/conversation_tags",
          schema: obj({ "name" => str }, required: %w[name])),
        t("get_chat_settings", "Fetch chat widget settings.", scope: "inbox", method: :get, path: "/chat_settings"),
        t("update_chat_settings", "Update chat widget settings.",
          scope: "inbox", method: :patch, path: "/chat_settings"),

        # ── socials ────────────────────────────────────────────────────────────
        t("list_social_regions", "List social content regions.", scope: "socials", method: :get, path: "/social_regions"),
        t("get_social_region", "Fetch a social region.",
          scope: "socials", method: :get, path: "/social_regions/{id}",
          path_params: %w[id], schema: obj({ "id" => int }, required: %w[id])),
        t("create_social_region", "Create a social content region.",
          scope: "socials", method: :post, path: "/social_regions",
          schema: obj({ "name" => str }, required: %w[name])),
        t("social_calendar", "Fetch a region's content calendar.",
          scope: "socials", method: :get, path: "/social_regions/{region_id}/calendar",
          path_params: %w[region_id], schema: obj({ "region_id" => int }, required: %w[region_id])),
        t("provision_social_content",
          "Fill a region's day with creative variants: copy plus feed (4:5) and/or reel (9:16) media " \
          "given as URLs the server downloads and attaches. This is the ONLY tool that attaches images/videos " \
          "to a post — create_social_post/update_social_post do not carry media. Identify the region by numeric " \
          "id or name. Pass replace=true to overwrite previously generated variants (manual uploads are kept).",
          scope: "socials", method: :post, path: "/socials/provision",
          schema: obj(
            { "region" => str("Region numeric id or (case-insensitive) name."),
              "date" => str("ISO date (YYYY-MM-DD) for the day to fill."),
              "replace" => { "type" => "boolean",
                             "description" => "Replace previously generated variants on the day." },
              "alternatives" => {
                "type" => "array",
                "description" => "One or more creative variants for the day.",
                "items" => obj(
                  { "headline" => str, "body" => str,
                    "cta_label" => str, "cta_url" => str,
                    "feed_media_url" => str("URL of the 4:5 feed image/video to download and attach."),
                    "reel_media_url" => str("URL of the 9:16 reel image/video to download and attach."),
                    "carousel_media_urls" => { "type" => "array", "items" => str,
                                               "description" => "Ordered image URLs for a native carousel." } })
              } },
            required: %w[region date alternatives])),
        t("create_social_post",
          "Create (or return) an empty scheduled day for a region. Only sets the date; add creative with " \
          "provision_social_content, then pick slots with update_social_post.",
          scope: "socials", method: :post, path: "/social_regions/{region_id}/social_posts",
          path_params: %w[region_id],
          schema: obj({ "region_id" => int, "date" => str("ISO date (YYYY-MM-DD).") },
                      required: %w[region_id date])),
        t("get_social_post", "Fetch a social post.",
          scope: "socials", method: :get, path: "/social_posts/{id}",
          path_params: %w[id], schema: obj({ "id" => int }, required: %w[id])),
        t("update_social_post",
          "Choose which variant fills each slot and/or mark the day ready. Does NOT set media or copy " \
          "(use provision_social_content / update_social_alternative for that).",
          scope: "socials", method: :patch, path: "/social_posts/{id}",
          path_params: %w[id],
          schema: obj({ "id" => int,
                        "feed_alternative_id" => int("Variant id to fill the feed slot (null to clear)."),
                        "reel_alternative_id" => int("Variant id to fill the reel slot (null to clear)."),
                        "carousel_alternative_id" => int("Variant id to fill the carousel slot (null to clear)."),
                        "post_hour" => int("Hour-of-day override for auto-posting (null to clear)."),
                        "ready" => bool }, required: %w[id])),
        t("update_social_alternative", "Edit a creative variant's copy (headline/body/CTA).",
          scope: "socials", method: :patch, path: "/social_alternatives/{id}",
          path_params: %w[id],
          schema: obj({ "id" => int, "headline" => str, "body" => str,
                        "cta_label" => str, "cta_url" => str }, required: %w[id])),
        t("delete_social_alternative", "Delete a creative variant (clears any slot it filled).",
          scope: "socials", method: :delete, path: "/social_alternatives/{id}",
          path_params: %w[id], schema: obj({ "id" => int }, required: %w[id])),
        t("post_social_alternative_now",
          "Publish one creative variant to the region's channels immediately, without changing the day's status.",
          scope: "socials", method: :post, path: "/social_alternatives/{id}/post_now",
          path_params: %w[id],
          schema: obj({ "id" => int, "slot" => str_enum(%w[feed reel]),
                        "channels" => { "type" => "array", "items" => str,
                                        "description" => "Subset of the region's channels (e.g. facebook, instagram, linkedin)." } },
                      required: %w[id])),
        t("publish_social_post_now", "Publish a social post immediately.",
          scope: "socials", method: :post, path: "/social_posts/{id}/publish_now",
          path_params: %w[id], schema: obj({ "id" => int }, required: %w[id])),
        t("social_post_deliveries", "List a social post's per-channel deliveries.",
          scope: "socials", method: :get, path: "/social_posts/{id}/deliveries",
          path_params: %w[id], schema: obj({ "id" => int }, required: %w[id])),

        # ── admin (account/user/environment management) ──────────────────────────
        t("list_users", "List account users.", scope: "admin", admin: true, method: :get, path: "/users"),
        t("get_user", "Fetch a user.",
          scope: "admin", admin: true, method: :get, path: "/users/{id}",
          path_params: %w[id], schema: obj({ "id" => int }, required: %w[id])),
        t("create_user", "Invite/create an account user.",
          scope: "admin", admin: true, method: :post, path: "/users",
          schema: obj({ "name" => str, "email" => str, "role" => str }, required: %w[name email])),
        t("update_user", "Update a user (role, name).",
          scope: "admin", admin: true, method: :patch, path: "/users/{id}",
          path_params: %w[id], schema: obj({ "id" => int, "name" => str, "role" => str }, required: %w[id])),
        t("delete_user", "Remove a user from the account.",
          scope: "admin", admin: true, method: :delete, path: "/users/{id}",
          path_params: %w[id], schema: obj({ "id" => int }, required: %w[id])),
        t("get_account", "Fetch account settings.",
          scope: "admin", admin: true, method: :get, path: "/accounts/{id}",
          path_params: %w[id], schema: obj({ "id" => int }, required: %w[id])),
        t("update_account", "Update account settings.",
          scope: "admin", admin: true, method: :patch, path: "/accounts/{id}",
          path_params: %w[id], schema: obj({ "id" => int, "name" => str,
                                             "message_retention_days" => int }, required: %w[id])),
        t("create_environment", "Create an environment.",
          scope: "admin", admin: true, method: :post, path: "/environments",
          schema: obj({ "name" => str, "tag" => str }, required: %w[name])),
        t("update_environment", "Update an environment.",
          scope: "admin", admin: true, method: :patch, path: "/environments/{id}",
          path_params: %w[id], schema: obj({ "id" => int, "name" => str }, required: %w[id]))
      ].freeze
    end

    def find(name)
      index[name]
    end

    def index
      @index ||= all.index_by(&:name)
    end

    # Tools visible to a grant: intersect granted scopes; hide admin tools from
    # non-admin users.
    def visible_to(scopes:, admin:)
      scopes = Array(scopes)
      all.select do |tool|
        scopes.include?(tool.scope) && (admin || !tool.admin?)
      end
    end

    # ── schema helpers ────────────────────────────────────────────────────────
    def t(name, description, scope:, method:, path:, admin: false, path_params: [], query: [], body_key: nil, schema: nil)
      Tool.new(
        name: name, description: description, scope: scope, admin: admin,
        method: method, path: path, path_params: path_params, query_params: query,
        body_key: body_key, input_schema: schema
      )
    end

    def obj(properties, required: [])
      s = { "type" => "object", "properties" => properties }
      s["required"] = required if required.present?
      s
    end

    def str(description = nil)
      description ? { "type" => "string", "description" => description } : { "type" => "string" }
    end

    def str_enum(values)
      { "type" => "string", "enum" => values }
    end

    def int(description = nil)
      description ? { "type" => "integer", "description" => description } : { "type" => "integer" }
    end

    def bool
      { "type" => "boolean" }
    end
  end
end
